apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc 
  project: default 
  source:
    path: cluster-config
    repoURL: https://github.com/georgenuesca/gitops-sample.git
    targetRevision: release
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
