apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-mf
  namespace: argocd
spec:
  destination:
    namespace: bgd
    server: https://kubernetes.default.svc 
  project: default 
  source:
    path: argocd-apps 
    repoURL: https://github.com/georgenuesca/gitops-sample.git
    targetRevision: master
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
